# Generated by Django 3.0.8 on 2020-08-11 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionPost',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.CharField(default=models.CharField(max_length=255, unique=True), max_length=255)),
                ('content', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('timeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('s', 'student'), ('t', 'teacher')], max_length=1)),
                ('time_available', models.CharField(max_length=200)),
                ('image', models.ImageField(default='default.jpg', upload_to='posts/images')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='posts/images')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.BlogComment')),
                ('tuitionpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.TuitionPost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
