# Generated by Django 3.0.8 on 2020-08-11 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_tuitionpost_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuitionpost',
            name='views',
        ),
        migrations.AddField(
            model_name='tuitionpost',
            name='views',
            field=models.ManyToManyField(related_name='post_view', to=settings.AUTH_USER_MODEL),
        ),
    ]
