# Generated by Django 3.0.8 on 2020-08-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprofile',
            name='city',
            field=models.ManyToManyField(related_name='city_set', to='classapp.Places'),
        ),
    ]
