# Generated by Django 3.0.8 on 2020-08-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0002_auto_20200812_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprofile',
            name='city',
            field=models.ManyToManyField(related_name='places_set', to='classapp.Places'),
        ),
    ]
