# Generated by Django 3.0.8 on 2020-08-10 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=13)),
                ('content', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('genre', models.CharField(choices=[('m', 'MALE'), ('f', 'FEMALE')], max_length=1)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=13)),
                ('locatity', models.CharField(max_length=30)),
                ('marital_status', models.CharField(choices=[('m', 'married'), ('u', 'Unmarried'), ('d', 'Divorced'), ('e', 'engaged'), ('s', 'separed')], max_length=1)),
                ('religion', models.CharField(max_length=50)),
                ('biodata', models.TextField()),
                ('category', models.CharField(choices=[('s', 'student'), ('t', 'teacher'), ('j', 'employee'), ('k', 'employery')], max_length=4, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='tuition/images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
