# Generated by Django 3.0.8 on 2020-09-22 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=13)),
                ('content', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SubDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdistrict', to='person.District')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('genre', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=13)),
                ('nationality', models.CharField(max_length=30)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried'), ('Divorced', 'Divorced'), ('Engaged', 'Engaged'), ('Separated', 'Separated')], max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('biodata', models.TextField()),
                ('profession', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Employee', 'Employee'), ('Employeer', 'Employeer')], max_length=50, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='tuition/images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TuitionClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', multiselectfield.db.fields.MultiSelectField(choices=[('Group_Tuition', 'Group Tuition'), ('Private_Tuition', 'Private Tuition')], max_length=100)),
                ('place', multiselectfield.db.fields.MultiSelectField(choices=[('Class_Rooms', 'Class Rooms'), ('Coaching_Center', 'Coaching Center'), ('Home_Visit', 'Home Visit'), ('My_Place', 'My Place')], max_length=100)),
                ('approach', multiselectfield.db.fields.MultiSelectField(choices=[('Online_Help', 'Online Help'), ('Phone_Help', 'Phone Help'), ('Provide_Hand_Notes', 'Provide Hand_Notes'), ('Video_Tutorials', 'Video Tutorials')], max_length=100)),
                ('medium', multiselectfield.db.fields.MultiSelectField(choices=[('Bangla_Medium', 'Bangla Medium'), ('English_Medium', 'English Medium'), ('Arabic_Medium', 'Arabic Medium'), ('Hindi_Medium', 'Hindi Medium'), ('Sports_Section', 'Sports Section'), ('Singing_Section', 'Singing Section'), ('Dance_Section', 'Dance Section'), ('Extra Curricular Activities', 'Extra Curricular Activities'), ('Language Learning', 'Language Learning'), ('Computer Learning', 'Computer Learning')], max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('days', models.CharField(max_length=100)),
                ('high_education', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy')], max_length=100)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district', to='person.District')),
                ('level', models.ManyToManyField(related_name='classes', to='person.Classes')),
                ('preferedPlace', models.ManyToManyField(related_name='city_set', to='person.SubDistrict')),
                ('subject', models.ManyToManyField(related_name='subjects', to='person.Subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tuitionclass', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SSC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('Science', 'Science'), ('Business_Studies', 'Business_Studies'), ('Humanities', 'Humanities')], max_length=100)),
                ('institute', models.CharField(max_length=200)),
                ('gpa', models.CharField(max_length=20)),
                ('board', models.CharField(max_length=20)),
                ('passing_year', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ssc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HSC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('Science', 'Science'), ('Business_Studies', 'Business_Studies'), ('Humanities', 'Humanities')], max_length=100)),
                ('institute', models.CharField(max_length=200)),
                ('gpa', models.CharField(max_length=20)),
                ('board', models.CharField(max_length=20)),
                ('passing_year', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hsc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HigherStudies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masters', models.CharField(max_length=200)),
                ('phd', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='higherstudies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AfterHsc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Etype', models.CharField(choices=[('Honours', 'Honours'), ('Degree', 'Degree'), ('Diploma', 'Diploma')], max_length=100)),
                ('degree', models.CharField(max_length=200)),
                ('institute', models.CharField(max_length=200)),
                ('cgpa', models.CharField(max_length=20)),
                ('passing_year', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='afterhsc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
