# Generated by Django 3.0.8 on 2020-08-11 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('person', '0002_afterhsc_higherstudies_hsc_ssc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SubDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TuitionClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', multiselectfield.db.fields.MultiSelectField(choices=[('Group_Tuition', 'Group_Tuition'), ('Private_Tuition', 'Private_Tuition')], max_length=100)),
                ('place', multiselectfield.db.fields.MultiSelectField(choices=[('Class_Rooms', 'Class_Rooms'), ('Coaching_Center', 'Coaching_Center'), ('Home_Visit', 'Home_Visit'), ('My_Place', 'My_Place')], max_length=100)),
                ('approach', multiselectfield.db.fields.MultiSelectField(choices=[('Online_Help', 'Online_Help'), ('Phone_Help', 'Phone_Help'), ('Provide_Hand_Notes', 'Provide_Hand_Notes'), ('Video_Tutorials', 'Video_Tutorials')], max_length=100)),
                ('medium', multiselectfield.db.fields.MultiSelectField(choices=[('Bangla_Medium', 'Online_Help'), ('English_Medium', 'Phone_Help'), ('Arabic_Medium', 'Provide_Hand_Notes'), ('Hindi_Medium', 'Video_Tutorials'), ('Sports_Section', 'Video_Tutorials'), ('Singing_Section', 'Video_Tutorials'), ('Dance_Section', 'Video_Tutorials'), ('Extra Curricular Activities', 'Video_Tutorials'), ('Language Learning', 'Video_Tutorials'), ('Computer Learning', 'Video_Tutorials')], max_length=100)),
                ('high_education', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy')], max_length=100)),
                ('days', models.CharField(max_length=100)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district', to='person.District')),
                ('level', models.ManyToManyField(related_name='classes', to='person.Classes')),
                ('subject', models.ManyToManyField(related_name='subject', to='person.Subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tuitionclass', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
