# Generated by Django 3.0.8 on 2020-08-11 02:42

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_classes_district_subdistrict_subject_tuitionclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdistrict',
            name='name',
        ),
        migrations.AddField(
            model_name='subdistrict',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subdistricts', to='person.District'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subdistrict',
            name='subdistrict',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tuitionclass',
            name='approach',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Online_Help', 'Online Help'), ('Phone_Help', 'Phone Help'), ('Provide_Hand_Notes', 'Provide Hand_Notes'), ('Video_Tutorials', 'Video Tutorials')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tuitionclass',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bangla_Medium', 'Bangla Medium'), ('English_Medium', 'English Medium'), ('Arabic_Medium', 'Arabic Medium'), ('Hindi_Medium', 'Hindi Medium'), ('Sports_Section', 'Sports Section'), ('Singing_Section', 'Singing Section'), ('Dance_Section', 'Dance Section'), ('Extra Curricular Activities', 'Extra Curricular Activities'), ('Language Learning', 'Language Learning'), ('Computer Learning', 'Computer Learning')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tuitionclass',
            name='place',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Class_Rooms', 'Class Rooms'), ('Coaching_Center', 'Coaching Center'), ('Home_Visit', 'Home Visit'), ('My_Place', 'My Place')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tuitionclass',
            name='style',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Group_Tuition', 'Group Tuition'), ('Private_Tuition', 'Private Tuition')], max_length=100),
        ),
    ]
