# Generated by Django 3.0.8 on 2020-08-12 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20200811_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subdistrict',
            old_name='subdistrict',
            new_name='name',
        ),
        migrations.AddField(
            model_name='tuitionclass',
            name='preferedPlace',
            field=models.ManyToManyField(null=True, related_name='city_set', to='person.SubDistrict'),
        ),
        migrations.AlterField(
            model_name='subdistrict',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdistrict', to='person.District'),
        ),
        migrations.AlterField(
            model_name='tuitionclass',
            name='level',
            field=models.ManyToManyField(null=True, related_name='classes', to='person.Classes'),
        ),
        migrations.AlterField(
            model_name='tuitionclass',
            name='subject',
            field=models.ManyToManyField(null=True, related_name='subject', to='person.Subject'),
        ),
    ]
