# Generated by Django 3.0.8 on 2020-08-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20200812_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionclass',
            name='level',
            field=models.ManyToManyField(related_name='classes', to='person.Classes'),
        ),
        migrations.AlterField(
            model_name='tuitionclass',
            name='preferedPlace',
            field=models.ManyToManyField(related_name='city_set', to='person.SubDistrict'),
        ),
        migrations.AlterField(
            model_name='tuitionclass',
            name='subject',
            field=models.ManyToManyField(related_name='subject', to='person.Subject'),
        ),
    ]
