# Generated by Django 3.0.8 on 2020-08-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20200824_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionclass',
            name='subject',
            field=models.ManyToManyField(related_name='subjects', to='person.Subject'),
        ),
    ]
