# Generated by Django 3.0.8 on 2020-08-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_auto_20200824_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='locatity',
            new_name='nationality',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='category',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Employee', 'Employee'), ('Employeer', 'Employeer')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='genre',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried'), ('Divorced', 'Divorced'), ('Engaged', 'Engaged'), ('Separated', 'Separated')], max_length=50),
        ),
    ]
