# Generated by Django 3.0.8 on 2020-09-22 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('person', '0002_auto_20200922_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(default='workless', max_length=100)),
                ('work_location', models.CharField(max_length=100)),
                ('employed_by', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('work_from', models.CharField(choices=[('Home', 'Home'), ('Work Place', 'Work Place')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='occupation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('fathers_occupation', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('mothers_occupation', models.CharField(max_length=100)),
                ('no_of_bro_sis', models.IntegerField()),
                ('family_type', models.CharField(choices=[('Joint', 'Joint'), ('Single', 'Single')], max_length=100)),
                ('family_status', models.CharField(choices=[('Affluent', 'Affluent'), ('Middle Class', 'Middle Class'), ('Rich', 'Rich')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('present_address', models.CharField(max_length=300)),
                ('permanent_address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=17)),
                ('is_phone_public', models.BooleanField(default=False)),
                ('birth_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth_country', to='metrimony.Country')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_district', to='person.District')),
                ('grow_up_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growup_country', to='metrimony.Country')),
                ('residency_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resi_country', to='metrimony.Country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
