# Generated by Django 3.0.8 on 2020-09-22 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metrimony', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_phone_public',
        ),
        migrations.RemoveField(
            model_name='address',
            name='phone',
        ),
        migrations.AlterField(
            model_name='family',
            name='family_type',
            field=models.CharField(choices=[('Joint', 'Joint'), ('Nuclear', 'Nuclear')], max_length=100),
        ),
        migrations.CreateModel(
            name='Personal_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('sir_name', models.CharField(max_length=100)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Never Married', 'Never Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Awaiting Divorces', 'Awaiting Divorces')], max_length=50)),
                ('phone', models.CharField(max_length=17)),
                ('is_phone_public', models.BooleanField(default=False)),
                ('religion', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=50)),
                ('biodata', models.TextField()),
                ('profile_photo', models.ImageField(default='default.jpg', upload_to='metrimony/images')),
                ('mother_tongue', models.CharField(max_length=150)),
                ('languages', models.ManyToManyField(to='metrimony.Language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
