# Generated by Django 3.0.8 on 2020-09-22 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metrimony', '0003_body_hobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='fav_color',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='fav_dress_style',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='interest',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='know_dancing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hobby',
            name='know_singing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hobby',
            name='music',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='read_books',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='sports',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='sports_shows',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='tv_shows',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='diet',
            field=models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal_info',
            name='do_u_drink',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='do_u_smoke',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='body',
            name='any_disability',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='hobbies',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Expectaion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.CharField(max_length=20)),
                ('max_age', models.CharField(max_length=20)),
                ('max_height', models.CharField(max_length=20)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Never Married', 'Never Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Awaiting Divorces', 'Awaiting Divorces')], max_length=100)),
                ('with_childern', models.BooleanField(default=False)),
                ('religion', models.CharField(max_length=100)),
                ('complexion', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('drinking_havits', models.BooleanField(default=False)),
                ('smoking_havits', models.BooleanField(default=False)),
                ('diet', models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian')], max_length=100)),
                ('residency_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expectaion_country', to='metrimony.Country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecpectation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
