# Generated by Django 3.0.8 on 2020-09-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrimony', '0005_education_height_profession_religion_sir_name_state_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='expectaion',
            name='min_height',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
