# Generated by Django 3.0.8 on 2020-09-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrimony', '0006_expectaion_min_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='birth_country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='grow_up_country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='residency_country',
            field=models.CharField(max_length=100),
        ),
    ]
