# Generated by Django 3.0.8 on 2020-09-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrimony', '0008_age_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='age',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='have_child',
            field=models.BooleanField(default=False),
        ),
    ]
