# Generated by Django 3.0.8 on 2020-09-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrimony', '0010_personal_info_highest_degree_of_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectaion',
            name='residency_country',
            field=models.CharField(max_length=100),
        ),
    ]
