# Generated by Django 3.0.8 on 2020-08-11 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(default='', max_length=40)),
                ('post_code', models.CharField(default='', max_length=50)),
                ('road_no', models.CharField(default='', max_length=50)),
                ('village', models.CharField(default='', max_length=50)),
                ('upozila', models.CharField(default='', max_length=50)),
                ('Zilla', models.CharField(default='', max_length=50)),
                ('division', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
                ('category', models.CharField(choices=[('a', 'Flat'), ('b', 'Room'), ('c', 'Any_space'), ('d', 'Land'), ('e', 'Shop'), ('f', 'Hostel_seat'), ('g', 'Company'), ('h', 'Building'), ('i', 'Bill_board'), ('j', 'Media_advertisement')], default='', max_length=1)),
                ('rent', models.IntegerField()),
                ('no_of_img', models.IntegerField(default=0)),
                ('area', models.CharField(default='', max_length=50)),
                ('text', models.TextField(max_length=500)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('view', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ToletComment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='tolet/images')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tolet.ToletComment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tolet.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='tolet/images')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tolet.Post')),
            ],
        ),
    ]
