# Generated by Django 3.0.8 on 2020-09-22 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tolet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tolet.Area'),
        ),
    ]
