# Generated by Django 3.0.8 on 2020-09-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolet', '0002_auto_20200922_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='area',
            field=models.CharField(max_length=300),
        ),
    ]
