# Generated by Django 3.0.8 on 2020-09-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolet', '0002_auto_20200811_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Flat', 'Flat'), ('Room', 'Room'), ('Any_space', 'Any_space'), ('Land', 'Land'), ('Shop', 'Shop'), ('Hostel_seat', 'Hostel_seat'), ('Company', 'Company'), ('Building', 'Building'), ('Bill_board', 'Bill_board'), ('Media_advertisement', 'Media_advertisement')], default='', max_length=100),
        ),
    ]
