# Generated by Django 3.0.8 on 2020-09-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolet', '0004_auto_20200922_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='area',
            field=models.CharField(max_length=300),
        ),
    ]
