# Generated by Django 3.0.8 on 2020-09-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolet', '0005_auto_20200922_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phone',
            field=models.CharField(default='', max_length=17),
        ),
    ]
